#!/usr/bin/env node

import fs from 'node:fs';
import crypto from 'node:crypto';
import { isDeepStrictEqual } from 'node:util';

const args = new Map();
const allowedArgs = new Set(['source', 'draft', 'shared', 'time-start-ms', 'time-end-ms']);
for (let i = 2; i < process.argv.length; i += 2) {
  const key = process.argv[i];
  const value = process.argv[i + 1];
  if (!key?.startsWith('--') || !allowedArgs.has(key.slice(2)) || args.has(key.slice(2)) || value === undefined) {
    failUsage();
  }
  args.set(key.slice(2), value);
}

const sourcePath = args.get('source');
const draftPath = args.get('draft');
const sharedPath = args.get('shared');
if (!sourcePath || !draftPath || !sharedPath) failUsage();

const timeStart = parseOptionalInteger(args.get('time-start-ms'));
const timeEnd = parseOptionalInteger(args.get('time-end-ms'));
if (timeStart === null || timeEnd === null) {
  failUsage();
}
if (timeStart > timeEnd) {
  throw new Error('--time-start-ms must be <= --time-end-ms');
}
if (timeEnd > Date.now()) {
  throw new Error('--time-end-ms cannot be in the future');
}

const maxExportGap = 60_000;

const markerPatterns = [
  /codex-browser-sidebar-comments-root/i,
  /\bopenai\b/i,
  /\bchatgpt\b/i,
  /\bcodex\b/i,
  /generated by/i,
  /\/Users\/[A-Za-z0-9._-]+\//,
  /\bevidence\//i,
  /build_annotation_state/i,
  /export_annotation_html/i,
  /sourceMappingURL/i,
  /\bplaywright\b/i,
  /chrome-devtools/i,
];

const forbiddenTrajectoryPatterns = [
  /生成并验证/,
  /生成并复核/,
  /产出最终产物/,
  /输出任务结果/,
  /定位任务所需输入文件/,
];

const files = {
  source: readHtml(sourcePath, false),
  draft: readHtml(draftPath, true),
  shared: readHtml(sharedPath, true),
};

const errors = [];
const warnings = [];

for (const kind of ['draft', 'shared']) {
  const codeSame = files.source.normalizedInlineScripts === files[kind].normalizedInlineScripts;
  if (!codeSame) {
    errors.push(`${kind}: inline JavaScript differs from source after PRESET_STATE normalization`);
  }
  if (!isDeepStrictEqual(files.source.scriptTags, files[kind].scriptTags)) {
    errors.push(`${kind}: script tag attributes differ from source`);
  }
  const changedHandlers = compareStaticHandlers(files.source.staticHandlers, files[kind].staticHandlers);
  if (changedHandlers.length) {
    errors.push(`${kind}: static inline event handlers differ from source (${changedHandlers.slice(0, 3).join(', ')})`);
  }
  for (const pattern of markerPatterns) {
    if (pattern.test(files[kind].text)) {
      if (pattern.test(files.source.text)) {
        warnings.push(`${kind}: marker ${pattern} also occurs in source; verify every occurrence against original task material`);
      } else {
        errors.push(`${kind}: direct internal/tool marker matched ${pattern}`);
      }
    }
  }
}

if (files.shared.state?._read_only !== true) {
  errors.push('shared: _read_only must be true');
}
if (files.draft.state?._read_only === true) {
  errors.push('draft: _read_only must not be true');
}

if (!isDeepStrictEqual(comparableState(files.draft.state), comparableState(files.shared.state))) {
  const keys = changedStateKeys(files.draft.state, files.shared.state);
  errors.push(`draft/shared: form state differs beyond native export fields (${keys.join(', ')})`);
}
const draftAccum = files.draft.state?._timer?.accum;
const sharedAccum = files.shared.state?._timer?.accum;
if (!Number.isSafeInteger(draftAccum) || !Number.isSafeInteger(sharedAccum) || draftAccum < 0 || sharedAccum < 0) {
  errors.push('draft/shared: _timer.accum must be a non-negative integer');
} else if (sharedAccum < draftAccum || sharedAccum - draftAccum > maxExportGap) {
  errors.push(`draft/shared: timer gap ${sharedAccum - draftAccum}ms is outside 0-${maxExportGap}ms`);
}

const draftSteps = files.draft.state?._traj_steps;
const sharedSteps = files.shared.state?._traj_steps;
if (!Array.isArray(draftSteps) || !Array.isArray(sharedSteps)) {
  errors.push('draft/shared: _traj_steps must be arrays');
} else {
  const draftIds = draftSteps.map((step) => String(step?.id ?? ''));
  const sharedIds = sharedSteps.map((step) => String(step?.id ?? ''));
  if (JSON.stringify(draftIds) !== JSON.stringify(sharedIds)) {
    errors.push('draft/shared: trajectory IDs differ');
  }
  if (new Set(sharedIds).size !== sharedIds.length) {
    errors.push('shared: trajectory IDs are not unique');
  }

  const millis = [];
  for (const id of sharedIds) {
    if (!/^ts_\d{13}$/.test(id)) {
      errors.push(`shared: non-native trajectory ID ${JSON.stringify(id)}`);
      continue;
    }
    const value = Number(id.slice(3));
    millis.push(value);
    if (value < timeStart) {
      errors.push(`shared: trajectory ID ${id} is before --time-start-ms`);
    }
    if (value > timeEnd) {
      errors.push(`shared: trajectory ID ${id} is after --time-end-ms`);
    }
    if (value > Date.now()) {
      errors.push(`shared: trajectory ID ${id} is in the future`);
    }
  }

  for (let i = 1; i < millis.length; i++) {
    if (millis[i] <= millis[i - 1]) {
      errors.push('shared: trajectory ID timestamps must be strictly increasing');
      break;
    }
  }
  if (millis.length >= 3) {
    const deltas = millis.slice(1).map((value, index) => value - millis[index]);
    if (new Set(deltas).size === 1) {
      errors.push('shared: trajectory ID timestamps form a mechanical equal-interval sequence');
    }
  }
  if (millis.length >= 2 && millis.every((value) => value % 1000 === 0)) {
    errors.push('shared: all trajectory ID timestamps fall on exact seconds');
  }

  for (const [index, step] of sharedSteps.entries()) {
    const text = `${step?.summary ?? ''}\n${step?.desc ?? ''}`;
    for (const pattern of forbiddenTrajectoryPatterns) {
      if (pattern.test(text)) {
        errors.push(`shared: trajectory step ${index + 1} matches forbidden wording ${pattern}`);
      }
    }
  }
}

const result = {
  ok: errors.length === 0,
  source: summarize(files.source),
  draft: summarize(files.draft),
  shared: summarize(files.shared),
  errors,
  warnings,
};

console.log(JSON.stringify(result, null, 2));
if (errors.length) process.exit(1);

function readHtml(filePath, requireState) {
  if (!fs.existsSync(filePath)) throw new Error(`file not found: ${filePath}`);
  const text = fs.readFileSync(filePath, 'utf8');
  const preset = locatePresetState(text);
  if (requireState && preset.state === null) {
    throw new Error(`PRESET_STATE is not a JSON object: ${filePath}`);
  }
  const normalizedText = text.slice(0, preset.start) + '{}' + text.slice(preset.end);
  return {
    path: filePath,
    text,
    state: preset.state,
    normalizedInlineScripts: extractInlineScripts(normalizedText),
    scriptTags: extractScriptTags(normalizedText),
    staticHandlers: extractStaticHandlers(text),
  };
}

function locatePresetState(text) {
  const key = 'const PRESET_STATE = ';
  const keyIndex = text.indexOf(key);
  if (keyIndex < 0) throw new Error('PRESET_STATE declaration not found');
  const start = keyIndex + key.length;
  if (text[start] !== '{') throw new Error('PRESET_STATE must start with an object');

  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let index = start; index < text.length; index++) {
    const char = text[index];
    if (inString) {
      if (escaped) escaped = false;
      else if (char === '\\') escaped = true;
      else if (char === '"') inString = false;
      continue;
    }
    if (char === '"') inString = true;
    else if (char === '{') depth++;
    else if (char === '}') {
      depth--;
      if (depth === 0) {
        const end = index + 1;
        return { start, end, state: JSON.parse(text.slice(start, end)) };
      }
    }
  }
  throw new Error('PRESET_STATE object is not terminated');
}

function extractInlineScripts(text) {
  const scripts = [];
  const pattern = /<script([^>]*)>([\s\S]*?)<\/script>/gi;
  let match;
  while ((match = pattern.exec(text))) {
    if (/\bsrc\s*=/i.test(match[1])) continue;
    scripts.push(match[2]);
  }
  return scripts.join('\n/*__INLINE_SCRIPT_BOUNDARY__*/\n');
}

function extractScriptTags(text) {
  const tags = [];
  const pattern = /<script\b([^>]*)>/gi;
  let match;
  while ((match = pattern.exec(text))) {
    tags.push(match[1].trim());
  }
  return tags;
}

function extractStaticHandlers(text) {
  // Exported pages add dynamic controls, so compare handlers on source controls
  // anchored by ID or by a unique class, plus counts for the remaining handlers.
  const elements = openingTags(text).map(({ tag, attrs }) => ({
    tag,
    id: readAttribute(attrs, 'id'),
    classes: (readAttribute(attrs, 'class') ?? '').split(/\s+/).filter(Boolean),
    handlers: [...attrs.matchAll(/\b(on[a-z]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/gi)]
      .map((match) => [match[1].toLowerCase(), match[2] ?? match[3] ?? match[4]]).sort(),
  }));
  return elements.filter((el) => el.id || el.handlers.length);
}

function compareStaticHandlers(source, exported) {
  const counts = new Map();
  const classCounts = new Map();
  for (const el of source) {
    for (const name of el.classes) {
      const key = `${el.tag}.${name}`;
      classCounts.set(key, (classCounts.get(key) ?? 0) + 1);
    }
  }
  for (const el of exported) {
    const signature = JSON.stringify([el.tag, el.handlers]);
    counts.set(signature, (counts.get(signature) ?? 0) + 1);
  }
  const missing = [];
  for (const el of source) {
    const signature = JSON.stringify([el.tag, el.handlers]);
    const count = counts.get(signature) ?? 0;
    if (!count) missing.push(signature);
    else counts.set(signature, count - 1);
    if (el.id) {
      const matches = exported.filter((item) => item.tag === el.tag && item.id === el.id);
      if (matches.length !== 1 || !isDeepStrictEqual(matches[0].handlers, el.handlers)) {
        missing.push(`${el.tag}#${el.id}`);
      }
    } else {
      const uniqueClass = el.classes.find((name) => classCounts.get(`${el.tag}.${name}`) === 1);
      if (uniqueClass) {
        const matches = exported.filter((item) => item.tag === el.tag && item.classes.includes(uniqueClass));
        if (matches.length !== 1 || !isDeepStrictEqual(matches[0].handlers, el.handlers)) {
          missing.push(`${el.tag}.${uniqueClass}`);
        }
      }
    }
  }
  return missing;
}

function openingTags(text) {
  const withoutScripts = text.replace(/<script\b[^>]*>[\s\S]*?<\/script\s*>/gi, '');
  const tags = [];
  for (let start = withoutScripts.indexOf('<'); start >= 0; start = withoutScripts.indexOf('<', start + 1)) {
    if (!/^<[a-z]/i.test(withoutScripts.slice(start, start + 2))) continue;
    let quote = null;
    let end = start + 1;
    for (; end < withoutScripts.length; end++) {
      const char = withoutScripts[end];
      if (quote) { if (char === quote) quote = null; }
      else if (char === '"' || char === "'") quote = char;
      else if (char === '>') break;
    }
    const match = /^<([\w:-]+)\b([\s\S]*)>$/.exec(withoutScripts.slice(start, end + 1));
    if (match) tags.push({ tag: match[1].toLowerCase(), attrs: match[2] });
    start = end;
  }
  return tags;
}

function readAttribute(attrs, name) {
  const match = new RegExp(`(?:^|\\s)${name}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s>]+))`, 'i').exec(attrs);
  return match ? (match[1] ?? match[2] ?? match[3]) : null;
}

function comparableState(state) {
  if (!state) return state;
  const { _read_only, _timer, ...rest } = state;
  return { ...rest, _timer: _timer && { ..._timer, accum: undefined } };
}

function changedStateKeys(draft, shared) {
  if (!draft || !shared) return ['PRESET_STATE'];
  const keys = new Set([...Object.keys(draft), ...Object.keys(shared)]);
  keys.delete('_read_only');
  keys.delete('_timer');
  return [...keys].filter((key) => !isDeepStrictEqual(draft[key], shared[key])).concat(
    isDeepStrictEqual({ ...draft._timer, accum: undefined }, { ...shared._timer, accum: undefined }) ? [] : ['_timer'],
  );
}

function summarize(file) {
  return {
    path: file.path,
    bytes: Buffer.byteLength(file.text),
    sha256: sha256(file.text),
    inline_script_sha256: sha256(file.normalizedInlineScripts),
    read_only: file.state?._read_only === true,
    timer: file.state?._timer ?? null,
    trajectory_ids: Array.isArray(file.state?._traj_steps)
      ? file.state._traj_steps.map((step) => step.id)
      : null,
  };
}

function sha256(value) {
  return crypto.createHash('sha256').update(value).digest('hex');
}

function parseOptionalInteger(value) {
  if (value === undefined) return null;
  if (!/^\d+$/.test(value)) throw new Error(`expected integer, got ${JSON.stringify(value)}`);
  const result = Number(value);
  if (!Number.isSafeInteger(result)) throw new Error(`integer is outside safe range: ${value}`);
  return result;
}

function failUsage() {
  console.error(
    'Usage: node validate_annotation_html_integrity.mjs --source <annotate.html> --draft <draft.html> --shared <shared.html> --time-start-ms <n> --time-end-ms <n>',
  );
  process.exit(2);
}
